export const FETCH_STOCKS = 'FETCH_STOCKS';
export const FETCH_DASHBOARD_DATA = 'FETCH_DASHBOARD_DATA';
export const FETCH_DASHBOARD_DATA_INIT = 'FETCH_DASHBOARD_DATA_INIT';
export const FETCH_DASHBOARD_DATA_SUCCESS = 'FETCH_DASHBOARD_DATA_SUCCESS';
export const FETCH_DASHBOARD_DATA_FAIL = 'FETCH_DASHBOARD_DATA_FAIL';

// More types to go here