export const FETCH_STOCKS = 'FETCH_STOCKS';
export const FETCH_DASHBOARD_DATA = 'FETCH_DASHBOARD_DATA';
export const FETCH_DASHBOARD_DATA_INIT = 'FETCH_DASHBOARD_DATA_INIT';
export const FETCH_DASHBOARD_DATA_SUCCESS = 'FETCH_DASHBOARD_DATA_SUCCESS';
export const FETCH_DASHBOARD_DATA_FAIL = 'FETCH_DASHBOARD_DATA_FAIL';

export const FETCH_TICKERS = 'FETCH_TICKERS';
export const FETCH_TICKERS_INIT = 'FETCH_TICKERS_INIT';
export const FETCH_TICKERS_SUCCESS = 'FETCH_TICKERS_SUCCESS';
export const FETCH_TICKERS_FAIL = 'FETCH_TICKERS_FAIL';

// More types to go here

